### ISSUE TITLE
Order entries and Section Associations filtering

### ISSUE THREAD

**Issue by andrewminton** [symphonists/order_entries#43]
Just something I noticed when adding Order Entries to a section connected with an SBL to my main content section.

When you re-order a filtered associated section entries, the order values are re-set to the count of entries in the associated filtered section.

i.e. Section Table index view:

Image|order=1
Image2|order=2
Image3|order=3
Image4|order=4

Filtered by project to only give me:

Image2|order=2
Image3|order=3

When re-ordered while still filtered by project:

Image3|order=1
Image2|order=2

Return to main index of section and you'll see:

Image|order=1
Image3|order=1
Image4|order=2
Image2|order=2

Is there another way of grabbing the value of the table index to get over this? so it only re-orders the numeric order value, rather than the table index' value. Does that make sense?

**Comment by jonmifsud** [comment]
@andrewminton I guess you didn't get around this correct?

I'll probably be giving this some love in the coming days, as I think it could be a useful addition to some things I'm working on.

Am I correct that you're interested in sorting according to your filters? If that's the intention do you still care about the `index view` sorting.

I am currently thinking of a scenario where a single item might me a member of multiple categories, yet would have to be sorted differently for each category. One possible solution is to store sort orders differently according to filters. The interesting thing is that the same 'order' has to be used when filtering in datasources.

not sure if @brendo might want to get involved in this discussion.

**Comment by andrewminton** [comment]
I haven't re-visited this yet Jon. But I think the index sort is still needed in most of my scenarios as well as. Per filter order does sound like a useful addition.

**Comment by jonmifsud** [comment]
@andrewminton I would still want to keep the index sorting, but would changing sorting within a filtered view, also change the sorting within the main section?

It's not a problem related to #17 because you have to many entries to sort within the 'main' list I guess.

**Comment by andrewminton** [comment]
@jonmifsud I'd still like it to change the sorting of the index list yes.. At present it doesn't do this.. only sorts the table of filtered entries starting at the entry index count of table entries instead of grabbing the first number of the filtered entry count. so I do think it needs a separate function when in a filtered context.

**Comment by jonmifsud** [comment]
ok I think it's related to the pagination concept. I plan of doing some work on this within the next couple of days. As it's probably something that will impact what I'm working on at the moment. 

Keep in Mind that after the steps you outlined below if I understand it will have these values:

i.e. Section Table index view:

Image|order=1
Image2|order=2
Image3|order=3
Image4|order=4

Filtered by project to only give me:

Image2|order=2
Image3|order=3

When re-ordered while still filtered by project:

Image3|order=1
Image2|order=3

Return to main index of section and you'll see:

Image|order=1
Image3|order=2
Image2|order=3
Image4|order=4

but if you wanted to filter the (other stuff)


Filtered by project to only give me:

Image1|order=1
Image4|order=4

When re-ordered while still filtered by project:

Image4|order=1
Image1|order=2

Return to main index of section and you'll see:

Image4|order=1
Image1|order=2
Image3|order=2
Image2|order=3

So you will still have to do some ordering the more items you wouldn't have in order the more complicated it would get. Not sure if there's a `clean` way to solve it. Filtered sorted views would start at an 'offset' of the first item and order subsequently.

**Comment by nitriques** [comment]
Great work guys!

**Comment by nilshoerrmann** [comment]
Is there a working (= production ready) fix for this already?

**Comment by nilshoerrmann** [comment]
This has been fixed thanks to @jonmifsud.
See version `2.2.0`.
