### ISSUE TITLE
Incompatible with "Ajax Checkbox" due to vague jquery selector

### ISSUE THREAD

**Issue by twiro** [symphonists/order_entries#59]
Order Entries (Latest Master with S2.5beta) seems to recalculate numbers based on the amount of "input"-elements found in the entries table. This results in wrong numbers when other input-elements (e.g. via "[Ajax Checkbox](https://github.com/DeuxHuitHuit/ajax_checkbox)") are added to the table.

Changing [line 78](https://github.com/symphonists/order_entries/blob/master/assets/order_entries.publish.js#L78) from...

    var items = table.find('input'),

to a more specific selector like...

    var items = table.find('input[id^="entry"]'),

...makes it work as expected again.

**Comment by nitriques** [comment]
Thanks Nils!

**Comment by nilshoerrmann** [comment]
:)
