### ISSUE TITLE
Filtered Sorting + Hidden Order Column

### ISSUE THREAD

**Issue by nilshoerrmann** [symphonists/order_entries#65]
Maybe this is something @jonmifsud could have a look into:
If you sort entries in filtered views, everything works fine as long as the column of the Order Entries field is shown in the section index. If the column is hidden the sort order gets scrambled randomly.

My guess is that the extension is relying on the column in the markup as storage but I haven't looked into. If that's the problem the current sorting order needs to be stored on the row instead to make it possible again to hide Order Entries columns.

**Comment by jonmifsud** [comment]
@nilshoerrmann correct - I thought sorting in general (regardless of filters) used to work in that way.

Maybe I can add a data attribute with the sort value when it's not made visible - but I'll have to look into that, agree it would be nice to hide the order number in most cases you don't need that to be visible.

**Comment by animaux** [comment]
Moving a page from a development- to a live-server has killed my sortorder. It was hidden in list view too so maybe this is a related problem.

**Comment by jonmifsud** [comment]
@animaux yes I think it's to do with the hidden order field. I presume this used to work before. I always left the sort order visible, will try to work on it / get a fix up today.

**Comment by animaux** [comment]
Many thanks Jon!

**Comment by nitriques** [comment]
Fixed integration via #68
