### ISSUE TITLE
Save fail in some circonstance

### ISSUE THREAD

**Issue by PascalPiche** [symphonists/order_entries#72]
strlen() expects parameter 1 to be string, array given
![bug_order-field](https://cloud.githubusercontent.com/assets/857498/9739472/dd49bf96-561d-11e5-8ae0-24d78b70c92f.jpg)

**Comment by PascalPiche** [comment]
May be in relation than my form got some errors, required field not filled. may generate an array of value than a single string for the order-entries value?. A quick fix was to add a check to remove de array

if (is_array($value)) {  
	$value = $value[0];  
}

**Comment by nitriques** [comment]
cc @jonmifsud by any chance, does it rings any bell ?

**Comment by jonmifsud** [comment]
Yes it does, sorry missed the original post. @nitriques thanks for the ping. @PascalPiche I think I should have pushed a fix for this on my branch. Issue basically lies in the fact that when using the filtering ability, there are multiple items. At least that's what I think it is. 

I don't have any errors on production with that version, if you still have issues can you confirm if you are using any 'filters' selected within the backend for the field. So I can try replicate the setup.

**Comment by nitriques** [comment]
Thanks a lot Jonathan.

**Comment by nitriques** [comment]
That branch I assume ? https://github.com/jonmifsud/order_entries/tree/fixorderxml

**Comment by jonmifsud** [comment]
Yep
