### ISSUE TITLE
Order saving error when xsrf enabled

### ISSUE THREAD

**Issue by jurajkapsz** [symphonists/order_entries#80]
When `enable_xsrf` is enabled in Symphony's `config.php` file, dragging index entries to reorder them results in an error:

    An error occured while saving the new sort order. Please try again.

The `.../extension/order_entries/save/?items[22]=1&items[16]=2...&xsrf=RDFnI%2FSxr2OgAh0WR0uK%2BU%2BBxnE` ajax call respond with a `HTTP 500`.

Disabling the xsrf setting in config file restores the functionality.

Symphony v2.6.7, Order Entries v2.3.3.

**Comment by michael-e** [comment]
I can not confirm this. Can you see the complete response you get?

**Comment by nitriques** [comment]
I can not reproduce (it works for me). Same versions.

This has been dealt with since [Symphony 2.4](https://github.com/symphonists/order_entries/commit/dcb0d0ff4bc5a65b5a3f2960f2d7eb9183cee6ef#diff-88eb23841d5b3e7c1302d275ec44cb35R55)

**Comment by munki-boy** [comment]
My installs agree with @nitriques (working since 2.4) does browser make a difference?

**Comment by nitriques** [comment]
> does browser make a difference?

Maybe, I tested Chrome on WIndows 7

**Comment by munki-boy** [comment]
FF win10 for me, working ok were we said it should.

**Comment by jurajkapsz** [comment]
Thanks, I will ship in more info. Looks like there is bit more to it.

I have encountered this on two different sites, but on one of them it looks like it is particular to a specific section while other sections there work.

Probably it is something in connection with the sections, although I am puzzled, because it happend on two different sites with two different sections. I will check out the common parts.

NB: It happend in Safari / Mac and e.g. Opera / Linux the same way.

**Comment by jurajkapsz** [comment]
Huh, maybe to correct the report title bit, I think the ordering works in general with `enable_xsrf` enabled, but I when I ran into this error, disabling the xsrf somehow helped.

Ok, will check it all once again.

**Comment by nitriques** [comment]
It keeps getting weird!

**Comment by jurajkapsz** [comment]
Ok, guys, I have no idea why it happens. But it happens.

I thought the `enable_xsrf` was a game changer as it influenced the saving issue in one case, but now I see that it keeps pn doing elsewhere within other sections or even the same section but with a filter applied.

I am facing this on three complete different hostings including my localhost and on two different sites. Not sure what I screwed this time.

Any tips what can I check and report? Maybe to start from scratch here. I have nothing in logs, just the yellow backend alert keeps showing up and in browser's debugger appears a HTTP 500 error message.

Thanks.

**Comment by jurajkapsz** [comment]
NB: I will compare `.htaccess` configs with other sites that are ok, maybe there are some conditions for this to happen, but I should have pretty much the same setups in general, but let's see...

**Comment by munki-boy** [comment]
I'm trying but I just can't break it here.

**Comment by nitriques** [comment]
@jurajkapsz Can you check for error in

1. Symphony's log
2. error_log file

A 500 normally creates one message in at least one of those..

**Comment by jurajkapsz** [comment]
Thanks @nitriques, I was lame about all those logs. In the meantime I found this out:

[These htaccess](https://github.com/h5bp/html5-boilerplate/blob/master/dist/.htaccess#L722-L727) instructions taken from h5bp caused this error log message:

    ... [core:alert] ... .htaccess: Invalid command 'text/css', perhaps misspelled or defined by a module not included in the server configuration, referer: ... /symphony/publish/...

I can't futher identify the issue, but the removal of this htaccess part removed the malfunction.

**Comment by munki-boy** [comment]
:sunglasses:

**Comment by nitriques** [comment]
:+1:

**Comment by jurajkapsz** [comment]
Thanks guys for your help and sorry for the mislead!

**Comment by nitriques** [comment]
> sorry for the mislead!

I prefer this then no reports at all :+1:

**Comment by jurajkapsz** [comment]
Cool :hand:

Thanks again!
