### ISSUE TITLE
Amok reordering on index reload

### ISSUE THREAD

**Issue by animaux** [symphonists/order_entries#81]
I get weird behavior on a site running `Symphony 2.6.7`and `Order Entries 2.3.3`. After reloading the index page the order is totally borked.

These are my section settings (no filtered ordering):

![bildschirmfoto 2016-03-02 um 15 34 58](https://cloud.githubusercontent.com/assets/446874/13463402/5ac83c42-e08c-11e5-9dce-fb6ff06934af.png)

This is the List after reordering manually:

![bildschirmfoto 2016-03-02 um 15 36 03](https://cloud.githubusercontent.com/assets/446874/13463436/851d24e4-e08c-11e5-9b34-a18d0790976a.png)

When I then reload the page the order is totally shuffled:

![bildschirmfoto 2016-03-02 um 15 36 15](https://cloud.githubusercontent.com/assets/446874/13463465/99c29b40-e08c-11e5-8d6d-b9f5722851ba.png)

**Comment by jonmifsud** [comment]
@animaux as discussed on Gitter looks like this is a separate issue with the database using a `varchar` instead of a `double` not sure if it's an actual Symphony bug.

**Comment by animaux** [comment]
Ok, I’ll close this :)
